# syntax=docker/dockerfile:1

FROM python:3.10.2-slim-buster
WORKDIR /app

ENV FLASK_APP=app.py
ENV FLASK_RUN_HOST=0.0.0.0
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

COPY ../.. .
COPY . .

RUN pip3 install -r requirements.txt
EXPOSE 5000


CMD ["flask", "run"]